name: MemorySMP
version: '1.0'
main: org.kazzleinc.memorySMP.MemorySMP
api-version: '1.21'
commands:
  testmembrane:
    usage: "/testmembrane"
  power1:
    usage: "/power1"
  power2:
    usage: "/power2"
  memory:
    aliases:
      - "mem"
    usage: "/memory [upgrade|info]"
